# Utiliser une image officielle PHP avec des extensions nécessaires
FROM php:8.2-cli

# Définir le répertoire de travail
WORKDIR /var/www/html

# Installer les extensions PHP nécessaires
RUN docker-php-ext-install pdo pdo_mysql
RUN apt-get update && \
    apt-get install -y libzip-dev unzip git && \
    docker-php-ext-install pdo pdo_mysql zip

# Installer Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Copier les fichiers de l'application dans le conteneur
COPY backend/ /var/www/html

# Assurer que le fichier artisan est exécutable
RUN chmod +x /var/www/html/artisan

# Assurer que les permissions sont correctes
RUN chown -R www-data:www-data /var/www/html

# Installer les dépendances PHP avec Composer (avec logs détaillés)
RUN composer install --verbose

# Exposer le port 9200
EXPOSE 10000

# Démarrer Laravel avec php artisan serve sur le port 9200 et exécuter les migrations
CMD php artisan serve --host=0.0.0.0 --port=${PORT:-10000} & \
    sleep 10 && \
    php artisan migrate --force
